### ISSUE TITLE
Añadir contenedores y configuración de Docker

### ISSUE THREAD

**Issue by AythaE** [AythaE/DeFesti#14]

**Comment by fblupi** [comment]
Se ha probado que funciona correctamente siguiendo las instrucciones proporcionadas:

![aythae-docker](https://cloud.githubusercontent.com/assets/6973564/21562171/e1806fc4-ce76-11e6-98bc-32a61a08d59e.png)

**Comment by pmmre** [comment]
Se ha comprobado que funciona correctamente:
![seleccion_025](https://cloud.githubusercontent.com/assets/14886093/21786689/85f60efa-d6c5-11e6-9ceb-29bab1f024e0.png)
